name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up swift packages
      run: swift package init --type library
    - name: Set up package for proj files
      run: swift package generate-xcodeproj    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
